import type { Achievement } from "@/lib/types";

export const ACHIEVEMENTS: Achievement[] = [
  // Mining — total taps
  {
    id: "taps-100",
    title: "Sparker",
    description: "Land 100 taps total.",
    category: "mining",
    rarity: "common",
    goal: 100,
    metric: "totalTaps",
    icon: "Sparkle",
    reward: { nackl: 50, xp: 30 },
  },
  {
    id: "taps-1k",
    title: "Forge-Worker",
    description: "Land 1,000 taps total.",
    category: "mining",
    rarity: "common",
    goal: 1000,
    metric: "totalTaps",
    icon: "Hammer",
    reward: { nackl: 250, xp: 100 },
  },
  {
    id: "taps-10k",
    title: "Iron Forge-Master",
    description: "Land 10,000 taps total.",
    category: "mining",
    rarity: "rare",
    goal: 10000,
    metric: "totalTaps",
    icon: "Flame",
    reward: { nackl: 1500, xp: 500 },
  },
  {
    id: "taps-100k",
    title: "Quantum Miner",
    description: "Land 100,000 taps total.",
    category: "mining",
    rarity: "epic",
    goal: 100000,
    metric: "totalTaps",
    icon: "Atom",
    reward: { nackl: 10000, xp: 2500 },
  },
  {
    id: "taps-1m",
    title: "Singularity Smith",
    description: "Land 1,000,000 taps total.",
    category: "mining",
    rarity: "mythic",
    goal: 1000000,
    metric: "totalTaps",
    icon: "Orbit",
    reward: { nackl: 100000, xp: 10000 },
  },

  // Sessions
  {
    id: "sessions-10",
    title: "Session Starter",
    description: "Complete 10 mining sessions.",
    category: "mining",
    rarity: "common",
    goal: 10,
    metric: "totalSessions",
    icon: "Repeat",
    reward: { nackl: 100, xp: 50 },
  },
  {
    id: "sessions-100",
    title: "Century Forge",
    description: "Complete 100 mining sessions.",
    category: "mining",
    rarity: "rare",
    goal: 100,
    metric: "totalSessions",
    icon: "Timer",
    reward: { nackl: 1000, xp: 400 },
  },
  {
    id: "sessions-1000",
    title: "Forge Veteran",
    description: "Complete 1,000 mining sessions.",
    category: "mining",
    rarity: "legendary",
    goal: 1000,
    metric: "totalSessions",
    icon: "Medal",
    reward: { nackl: 15000, xp: 3000 },
  },

  // Epochs
  {
    id: "epochs-1",
    title: "Epoch One",
    description: "Fill your first 5-minute epoch.",
    category: "mining",
    rarity: "common",
    goal: 1,
    metric: "totalEpochs",
    icon: "Timer",
    reward: { nackl: 200, xp: 75 },
  },
  {
    id: "epochs-50",
    title: "Epoch Engineer",
    description: "Fill 50 complete epochs.",
    category: "mining",
    rarity: "epic",
    goal: 50,
    metric: "totalEpochs",
    icon: "CalendarClock",
    reward: { nackl: 5000, xp: 1500 },
  },

  // Rewards
  {
    id: "rewards-1k",
    title: "First Thousand",
    description: "Claim 1,000 Nackl in rewards.",
    category: "milestone",
    rarity: "common",
    goal: 1000,
    metric: "totalRewards",
    icon: "Coins",
    reward: { nackl: 200, xp: 50 },
  },
  {
    id: "rewards-100k",
    title: "Nackl Tycoon",
    description: "Claim 100,000 Nackl in rewards.",
    category: "milestone",
    rarity: "legendary",
    goal: 100000,
    metric: "totalRewards",
    icon: "Gem",
    reward: { nackl: 25000, xp: 5000 },
  },
  {
    id: "rewards-1m",
    title: "Nackl Magnate",
    description: "Claim 1,000,000 Nackl in rewards.",
    category: "milestone",
    rarity: "mythic",
    goal: 1000000,
    metric: "totalRewards",
    icon: "Crown",
    reward: { nackl: 250000, xp: 25000 },
  },

  // Level milestones
  {
    id: "level-5",
    title: "Apprentice",
    description: "Reach level 5.",
    category: "milestone",
    rarity: "common",
    goal: 5,
    metric: "level",
    icon: "Star",
    reward: { nackl: 250, xp: 0 },
  },
  {
    id: "level-25",
    title: "Journeyman",
    description: "Reach level 25.",
    category: "milestone",
    rarity: "rare",
    goal: 25,
    metric: "level",
    icon: "Star",
    reward: { nackl: 2000, xp: 0 },
  },
  {
    id: "level-50",
    title: "Master Forge-Smith",
    description: "Reach level 50.",
    category: "milestone",
    rarity: "epic",
    goal: 50,
    metric: "level",
    icon: "Award",
    reward: { nackl: 10000, xp: 0 },
  },
  {
    id: "level-100",
    title: "Grand Forge-Master",
    description: "Reach level 100.",
    category: "milestone",
    rarity: "mythic",
    goal: 100,
    metric: "level",
    icon: "Crown",
    reward: { nackl: 100000, xp: 0 },
  },

  // Collection
  {
    id: "equip-5",
    title: "Collector",
    description: "Own 5 pieces of equipment.",
    category: "collection",
    rarity: "common",
    goal: 5,
    metric: "ownedEquipment",
    icon: "Package",
    reward: { nackl: 500, xp: 150 },
  },
  {
    id: "equip-15",
    title: "Arsenal",
    description: "Own 15 pieces of equipment.",
    category: "collection",
    rarity: "rare",
    goal: 15,
    metric: "ownedEquipment",
    icon: "Boxes",
    reward: { nackl: 3000, xp: 800 },
  },
  {
    id: "equip-all",
    title: "Forge Completionist",
    description: "Own every piece of equipment in the forge.",
    category: "collection",
    rarity: "mythic",
    goal: 22,
    metric: "ownedEquipment",
    icon: "Trophy",
    reward: { nackl: 200000, xp: 15000 },
  },

  // Social
  {
    id: "ref-1",
    title: "Recruiter",
    description: "Refer 1 friend to NacklForge.",
    category: "social",
    rarity: "common",
    goal: 1,
    metric: "referrals",
    icon: "UserPlus",
    reward: { nackl: 500, xp: 200 },
  },
  {
    id: "ref-10",
    title: "Network Builder",
    description: "Refer 10 friends to NacklForge.",
    category: "social",
    rarity: "epic",
    goal: 10,
    metric: "referrals",
    icon: "Users",
    reward: { nackl: 10000, xp: 2500 },
  },
  {
    id: "ref-100",
    title: "Forge Ambassador",
    description: "Refer 100 friends to NacklForge.",
    category: "social",
    rarity: "mythic",
    goal: 100,
    metric: "referrals",
    icon: "Megaphone",
    reward: { nackl: 200000, xp: 20000 },
  },

  // Streak
  {
    id: "streak-7",
    title: "Week Warrior",
    description: "Maintain a 7-day streak.",
    category: "milestone",
    rarity: "rare",
    goal: 7,
    metric: "streak",
    icon: "Flame",
    reward: { nackl: 1500, xp: 400 },
  },
  {
    id: "streak-30",
    title: "Unbreakable",
    description: "Maintain a 30-day streak.",
    category: "milestone",
    rarity: "legendary",
    goal: 30,
    metric: "streak",
    icon: "Flame",
    reward: { nackl: 15000, xp: 4000 },
  },
];

export const ACHIEVEMENTS_BY_ID: Record<string, Achievement> = Object.fromEntries(
  ACHIEVEMENTS.map((a) => [a.id, a]),
);
