import type { BoosterDef } from "@/lib/types";

export const BOOSTERS: BoosterDef[] = [
  {
    id: "turbo",
    name: "Turbo Tap",
    description: "Doubles tap output for 60 seconds.",
    durationMs: 60_000,
    effect: "tap_multiplier",
    magnitude: 2.0,
    icon: "Zap",
    accent: "amber",
    cost: 500,
  },
  {
    id: "double-reward",
    name: "Golden Hour",
    description: "Doubles all reward claims for 5 minutes.",
    durationMs: 5 * 60_000,
    effect: "reward_multiplier",
    magnitude: 2.0,
    icon: "Coins",
    accent: "lime",
    cost: 1200,
  },
  {
    id: "cooldown-skip",
    name: "Overclock",
    description: "Skips all cooldowns for 90 seconds.",
    durationMs: 90_000,
    effect: "cooldown_skip",
    magnitude: 1.0,
    icon: "FastForward",
    accent: "cyan",
    cost: 800,
  },
  {
    id: "auto-tap",
    name: "Auto-Forge",
    description: "Auto-taps at maximum rate for 30 seconds.",
    durationMs: 30_000,
    effect: "auto_tap",
    magnitude: 1.0,
    icon: "Bot",
    accent: "magenta",
    cost: 1500,
  },
  {
    id: "triple-tap",
    name: "Singularity Surge",
    description: "Triples tap output for 30 seconds.",
    durationMs: 30_000,
    effect: "tap_multiplier",
    magnitude: 3.0,
    icon: "Orbit",
    accent: "magenta",
    cost: 2500,
  },
  {
    id: "mega-reward",
    name: "Nackl Storm",
    description: "5x reward claims for 2 minutes.",
    durationMs: 2 * 60_000,
    effect: "reward_multiplier",
    magnitude: 5.0,
    icon: "Crown",
    accent: "amber",
    cost: 6000,
  },
];

export const BOOSTERS_BY_ID: Record<string, BoosterDef> = Object.fromEntries(
  BOOSTERS.map((b) => [b.id, b]),
);
