import type { EquipmentItem, Rarity } from "@/lib/types";

export const RARITY_COLORS: Record<Rarity, { text: string; border: string; bg: string; glow: string }> = {
  common: {
    text: "text-zinc-300",
    border: "border-zinc-500/40",
    bg: "bg-zinc-500/10",
    glow: "shadow-[0_0_20px_oklch(0.7_0.02_280/20%)]",
  },
  rare: {
    text: "text-cyan-300",
    border: "border-cyan-400/50",
    bg: "bg-cyan-500/10",
    glow: "shadow-[0_0_24px_oklch(0.75_0.18_195/35%)]",
  },
  epic: {
    text: "text-fuchsia-300",
    border: "border-fuchsia-400/50",
    bg: "bg-fuchsia-500/10",
    glow: "shadow-[0_0_28px_oklch(0.7_0.25_330/40%)]",
  },
  legendary: {
    text: "text-amber-300",
    border: "border-amber-400/60",
    bg: "bg-amber-500/15",
    glow: "shadow-[0_0_32px_oklch(0.78_0.2_70/45%)]",
  },
  mythic: {
    text: "text-lime-300",
    border: "border-lime-400/70",
    bg: "bg-lime-500/15",
    glow: "shadow-[0_0_36px_oklch(0.75_0.2_130/50%)]",
  },
};

export const RARITY_LABEL: Record<Rarity, string> = {
  common: "Common",
  rare: "Rare",
  epic: "Epic",
  legendary: "Legendary",
  mythic: "Mythic",
};

export const EQUIPMENT: EquipmentItem[] = [
  // RIG SLOT — core tap multiplier
  {
    id: "rig-starter",
    slot: "rig",
    name: "Apprentice Hammer",
    description: "A basic forging hammer. Everyone starts here.",
    rarity: "common",
    tier: 1,
    cost: 0,
    tapMultiplier: 1.0,
    cooldownReductionMs: 0,
    rewardMultiplier: 1.0,
    icon: "Hammer",
    accent: "amber",
  },
  {
    id: "rig-bronze",
    slot: "rig",
    name: "Bronze Forge Hammer",
    description: "Heavier head, more sparks per strike.",
    rarity: "common",
    tier: 2,
    cost: 250,
    tapMultiplier: 1.25,
    cooldownReductionMs: 0,
    rewardMultiplier: 1.0,
    icon: "Hammer",
    accent: "amber",
  },
  {
    id: "rig-iron",
    slot: "rig",
    name: "Iron Power Drill",
    description: "Mechanized drilling for sustained tap output.",
    rarity: "rare",
    tier: 3,
    cost: 1500,
    tapMultiplier: 1.6,
    cooldownReductionMs: 200,
    rewardMultiplier: 1.05,
    icon: "Drill",
    accent: "cyan",
  },
  {
    id: "rig-plasma",
    slot: "rig",
    name: "Plasma Cutter",
    description: "Ionized plasma jet melts through Nackl ore.",
    rarity: "epic",
    tier: 4,
    cost: 8000,
    tapMultiplier: 2.2,
    cooldownReductionMs: 400,
    rewardMultiplier: 1.15,
    icon: "Flame",
    accent: "magenta",
  },
  {
    id: "rig-quantum",
    slot: "rig",
    name: "Quantum Resonator",
    description: "Taps into quantum fluctuations to multiply yield.",
    rarity: "legendary",
    tier: 5,
    cost: 40000,
    tapMultiplier: 3.4,
    cooldownReductionMs: 800,
    rewardMultiplier: 1.3,
    icon: "Atom",
    accent: "amber",
  },
  {
    id: "rig-singularity",
    slot: "rig",
    name: "Singularity Core",
    description: "A contained micro-black hole. Bends time and ore.",
    rarity: "mythic",
    tier: 6,
    cost: 200000,
    tapMultiplier: 5.5,
    cooldownReductionMs: 1500,
    rewardMultiplier: 1.6,
    icon: "Orbit",
    accent: "lime",
  },

  // COOLING SLOT — cooldown reduction
  {
    id: "cool-fan",
    slot: "cooling",
    name: "Stock Heatsink",
    description: "Basic aluminum heatsink. Better than nothing.",
    rarity: "common",
    tier: 1,
    cost: 0,
    tapMultiplier: 1.0,
    cooldownReductionMs: 0,
    rewardMultiplier: 1.0,
    icon: "Fan",
    accent: "amber",
  },
  {
    id: "cool-liquid",
    slot: "cooling",
    name: "Liquid Coolant Loop",
    description: "Closed-loop liquid cooling keeps the rig frosty.",
    rarity: "rare",
    tier: 2,
    cost: 3000,
    tapMultiplier: 1.0,
    cooldownReductionMs: 600,
    rewardMultiplier: 1.0,
    icon: "Droplets",
    accent: "cyan",
  },
  {
    id: "cool-cryo",
    slot: "cooling",
    name: "Cryogenic Chamber",
    description: "Sub-zero cooling enables sustained overclock.",
    rarity: "epic",
    tier: 3,
    cost: 18000,
    tapMultiplier: 1.0,
    cooldownReductionMs: 1400,
    rewardMultiplier: 1.1,
    icon: "Snowflake",
    accent: "cyan",
  },
  {
    id: "cool-absolute",
    slot: "cooling",
    name: "Absolute Zero Unit",
    description: "Approaches 0K. Time itself slows inside the rig.",
    rarity: "legendary",
    tier: 4,
    cost: 90000,
    tapMultiplier: 1.0,
    cooldownReductionMs: 2500,
    rewardMultiplier: 1.2,
    icon: "Snowflake",
    accent: "amber",
  },

  // POWER SLOT — reward multiplier
  {
    id: "pow-grid",
    slot: "power",
    name: "Grid Connection",
    description: "Standard wall power. Reliable but unremarkable.",
    rarity: "common",
    tier: 1,
    cost: 0,
    tapMultiplier: 1.0,
    cooldownReductionMs: 0,
    rewardMultiplier: 1.0,
    icon: "Plug",
    accent: "amber",
  },
  {
    id: "pow-solar",
    slot: "power",
    name: "Solar Array",
    description: "Renewable energy from the forge roof.",
    rarity: "rare",
    tier: 2,
    cost: 4500,
    tapMultiplier: 1.0,
    cooldownReductionMs: 0,
    rewardMultiplier: 1.15,
    icon: "Sun",
    accent: "lime",
  },
  {
    id: "pow-fusion",
    slot: "power",
    name: "Fusion Reactor",
    description: "Compact fusion core. Endless clean energy.",
    rarity: "epic",
    tier: 3,
    cost: 22000,
    tapMultiplier: 1.0,
    cooldownReductionMs: 300,
    rewardMultiplier: 1.35,
    icon: "Atom",
    accent: "magenta",
  },
  {
    id: "pow-antimatter",
    slot: "power",
    name: "Antimatter Cell",
    description: "Matter-antimatter annihilation yields absurd output.",
    rarity: "legendary",
    tier: 4,
    cost: 110000,
    tapMultiplier: 1.0,
    cooldownReductionMs: 600,
    rewardMultiplier: 1.7,
    icon: "Zap",
    accent: "amber",
  },

  // AMPLIFIER SLOT — boost both tap and reward slightly
  {
    id: "amp-basic",
    slot: "amplifier",
    name: "Signal Booster",
    description: "Amplifies the tap signal sent to the chain.",
    rarity: "common",
    tier: 1,
    cost: 1000,
    tapMultiplier: 1.1,
    cooldownReductionMs: 100,
    rewardMultiplier: 1.05,
    icon: "Radio",
    accent: "cyan",
  },
  {
    id: "amp-resonance",
    slot: "amplifier",
    name: "Resonance Crystal",
    description: "Tunes the rig to the natural frequency of Nackl ore.",
    rarity: "rare",
    tier: 2,
    cost: 6000,
    tapMultiplier: 1.2,
    cooldownReductionMs: 250,
    rewardMultiplier: 1.12,
    icon: "Gem",
    accent: "magenta",
  },
  {
    id: "amp-harmonic",
    slot: "amplifier",
    name: "Harmonic Inducer",
    description: "Multi-frequency harmonic wave driver.",
    rarity: "epic",
    tier: 3,
    cost: 28000,
    tapMultiplier: 1.35,
    cooldownReductionMs: 500,
    rewardMultiplier: 1.2,
    icon: "AudioWaveform",
    accent: "violet",
  },
  {
    id: "amp-overdrive",
    slot: "amplifier",
    name: "Overdrive Coil",
    description: "Pushes the rig past its rated limits. Safely. Mostly.",
    rarity: "legendary",
    tier: 4,
    cost: 140000,
    tapMultiplier: 1.6,
    cooldownReductionMs: 900,
    rewardMultiplier: 1.35,
    icon: "TrendingUp",
    accent: "amber",
  },

  // BOOSTER SLOT — misc multiplier
  {
    id: "boost-lucky",
    slot: "booster",
    name: "Lucky Charm",
    description: "A small trinket. Occasionally doubles a tap.",
    rarity: "rare",
    tier: 1,
    cost: 2500,
    tapMultiplier: 1.15,
    cooldownReductionMs: 0,
    rewardMultiplier: 1.08,
    icon: "Clover",
    accent: "lime",
  },
  {
    id: "boost-rune",
    slot: "booster",
    name: "Ancient Nackl Rune",
    description: "Inscribed with the lost language of the first miners.",
    rarity: "epic",
    tier: 2,
    cost: 15000,
    tapMultiplier: 1.3,
    cooldownReductionMs: 400,
    rewardMultiplier: 1.18,
    icon: "Scroll",
    accent: "magenta",
  },
  {
    id: "boost-relic",
    slot: "booster",
    name: "Relic of the Forge",
    description: "A legendary artifact from the founding Nacklforge.",
    rarity: "mythic",
    tier: 3,
    cost: 175000,
    tapMultiplier: 1.7,
    cooldownReductionMs: 1000,
    rewardMultiplier: 1.45,
    icon: "Crown",
    accent: "lime",
  },
];

export const EQUIPMENT_BY_ID: Record<string, EquipmentItem> = Object.fromEntries(
  EQUIPMENT.map((e) => [e.id, e]),
);

export const STARTER_EQUIPMENT_IDS = ["rig-starter", "cool-fan", "pow-grid"];

export const SLOT_LABELS: Record<string, string> = {
  rig: "Mining Rig",
  cooling: "Cooling System",
  power: "Power Source",
  amplifier: "Amplifier",
  booster: "Booster",
};

export const SLOT_ICONS: Record<string, string> = {
  rig: "Hammer",
  cooling: "Snowflake",
  power: "Zap",
  amplifier: "Radio",
  booster: "Sparkles",
};
