import type { Quest } from "@/lib/types";

export const QUESTS: Omit<Quest, "progress" | "completed" | "claimed">[] = [
  // DAILY — mining
  {
    id: "daily-taps-50",
    title: "Daily Grind",
    description: "Land 50 taps today.",
    type: "daily",
    category: "mining",
    goal: 50,
    reward: { nackl: 100, xp: 50 },
    icon: "Hammer",
    accent: "amber",
  },
  {
    id: "daily-taps-200",
    title: "Forge Frenzy",
    description: "Land 200 taps in a single day.",
    type: "daily",
    category: "mining",
    goal: 200,
    reward: { nackl: 400, xp: 150 },
    icon: "Flame",
    accent: "magenta",
  },
  {
    id: "daily-sessions-5",
    title: "Session Streaker",
    description: "Complete 5 mining sessions today.",
    type: "daily",
    category: "mining",
    goal: 5,
    reward: { nackl: 200, xp: 80 },
    icon: "Repeat",
    accent: "cyan",
  },
  {
    id: "daily-epoch-full",
    title: "Epoch Crusher",
    description: "Fill a complete 5-minute epoch (70 taps).",
    type: "daily",
    category: "mining",
    goal: 1,
    reward: { nackl: 600, xp: 200 },
    icon: "Timer",
    accent: "amber",
  },

  // DAILY — economic
  {
    id: "daily-buy-equipment",
    title: "Forge Upgrade",
    description: "Buy or upgrade one piece of equipment today.",
    type: "daily",
    category: "economic",
    goal: 1,
    reward: { nackl: 150, xp: 60 },
    icon: "ShoppingBag",
    accent: "cyan",
  },
  {
    id: "daily-activate-booster",
    title: "Power Surge",
    description: "Activate any booster today.",
    type: "daily",
    category: "economic",
    goal: 1,
    reward: { nackl: 120, xp: 50 },
    icon: "Zap",
    accent: "magenta",
  },

  // DAILY — social
  {
    id: "daily-share",
    title: "Spread the Word",
    description: "Share your referral code (button click).",
    type: "daily",
    category: "social",
    goal: 1,
    reward: { nackl: 80, xp: 40 },
    icon: "Share2",
    accent: "lime",
  },

  // WEEKLY
  {
    id: "weekly-taps-2000",
    title: "Weekly Marathon",
    description: "Land 2000 taps this week.",
    type: "weekly",
    category: "mining",
    goal: 2000,
    reward: { nackl: 3000, xp: 800 },
    icon: "Mountain",
    accent: "amber",
  },
  {
    id: "weekly-streak-7",
    title: "Loyal Forge-Worker",
    description: "Maintain a 7-day login streak.",
    type: "weekly",
    category: "progression",
    goal: 7,
    reward: { nackl: 5000, xp: 1200 },
    icon: "Calendar",
    accent: "magenta",
  },
  {
    id: "weekly-spend-10k",
    title: "Big Spender",
    description: "Spend 10,000 Nackl on equipment this week.",
    type: "weekly",
    category: "economic",
    goal: 10000,
    reward: { nackl: 2500, xp: 600 },
    icon: "Coins",
    accent: "cyan",
  },

  // ONE-TIME — progression
  {
    id: "once-first-tap",
    title: "First Spark",
    description: "Land your first tap on the forge.",
    type: "one-time",
    category: "progression",
    goal: 1,
    reward: { nackl: 50, xp: 25 },
    icon: "Sparkle",
    accent: "amber",
  },
  {
    id: "once-first-session",
    title: "First Forge",
    description: "Complete your first mining session.",
    type: "one-time",
    category: "progression",
    goal: 1,
    reward: { nackl: 100, xp: 50 },
    icon: "CheckCircle",
    accent: "cyan",
  },
  {
    id: "once-first-equipment",
    title: "First Upgrade",
    description: "Buy your first piece of equipment.",
    type: "one-time",
    category: "progression",
    goal: 1,
    reward: { nackl: 200, xp: 75 },
    icon: "TrendingUp",
    accent: "lime",
  },
  {
    id: "once-first-referral",
    title: "Bring a Friend",
    description: "Get your first referral.",
    type: "one-time",
    category: "social",
    goal: 1,
    reward: { nackl: 1000, xp: 300 },
    icon: "UserPlus",
    accent: "magenta",
  },
  {
    id: "once-level-10",
    title: "Rising Forge-Master",
    description: "Reach level 10.",
    type: "one-time",
    category: "progression",
    goal: 10,
    reward: { nackl: 2000, xp: 0 },
    icon: "Crown",
    accent: "amber",
  },
];

export const QUESTS_BY_ID: Record<string, Omit<Quest, "progress" | "completed" | "claimed">> =
  Object.fromEntries(QUESTS.map((q) => [q.id, q]));
